### ISSUE TITLE
regenerate the wav file  after the augmentation

### ISSUE THREAD

**Issue by Aishaj** [TeaPoly/SpectrumAugmenter#2]
Hi, 
I'm trying to extend this code and regenerate the wav file from the spectrogram after the augmentation.  I added the below line at line 85 
`wav=librosa.feature.inverse.mel_to_audio(warped_masked_spectrogram)`

However, I'm getting the following error .. any idea how this can be fixed?
`Traceback (most recent call last):
  File "optuna.py", line 512, in <module>
    main(sys.argv[1:])
  File "optuna.py", line 427, in main
    X_train, y_train , X_test ,  y_test  = create_dataset(path)
  File "optuna.py", line 76, in create_dataset
    extract_features(wav, cls, model, samples , labels , aug_samples , aug_labels )
  File "optuna.py", line 366, in extract_features
    wav=librosa.feature.inverse.mel_to_audio(warped_masked_spectrogram)
  File "C:\Users\ash_j\anaconda3\envs\yamnet\lib\site-packages\librosa\feature\inverse.py", line 172, in mel_to_audio
    stft = mel_to_stft(M, sr=sr, n_fft=n_fft, power=power, **kwargs)
  File "C:\Users\ash_j\anaconda3\envs\yamnet\lib\site-packages\librosa\feature\inverse.py", line 83, in mel_to_stft
    mel_basis = filters.mel(sr, n_fft, n_mels=M.shape[0], dtype=M.dtype, **kwargs)
  File "C:\Users\ash_j\anaconda3\envs\yamnet\lib\site-packages\librosa\filters.py", line 209, in mel
    weights = np.zeros((n_mels, int(1 + n_fft // 2)), dtype=dtype)
TypeError: Cannot interpret 'tf.float32' as a data type`

**Comment by TeaPoly** [comment]
Trying to convert `warped_masked_spectrogram `(types is `tf.tensor`) to `numpy.array`.

**Comment by Aishaj** [comment]
Thanks, it worked but it took 8 hours and still didn't finish converting.  I'll share a new issue in a new post. 
Thanks
